language: java
jdk:
- oraclejdk8
script: ant dist
deploy:
  provider: releases
  api_key:
    secure: "FKl1RhQHErfUYdWe+fRNyMhoaJepchYNPTatPYca6sVfbkoomGTzVLD2jaafBkvnBgCmqiI9OvAtrRZgP5i30XoWh+9/tIIDr7miXM2PzLW6sBgabR+axymHhtskjSqv0hxwqxLp7O7p4C2fNwtSP/v7xJnFPMEqzRt6ORmNdq0="
  file: dist/cfr-pentaho5/*
  file_glob: true
  skip_cleanup: true
  on:
    branch: release-5
    repo: webdetails/cfr
