language: java
jdk:
- oraclejdk8
script: ant dist
deploy:
  provider: releases
  api_key:
    secure: "coEkQHEwmMYWGtc0wjNJtVYdEFfHpOLy6GQ7e5A215B3o/410IacRisdant3rORyhBjWOGvLfv8596YMOupjzufAr+V7JrX5hoJa+550+lAqUEHTGGI38SiAzI+l9UaWG41mPJYgXzDwLAMgANGpgyyR8hA1Hwr1XLORVBgGN/A="
  file: dist/cfr-pentaho5/*
  file_glob: true
  skip_cleanup: true
  on:
    branch: release-5
    repo: webdetails/cfr
